/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{													//Pg 51, 52, 166, 243, 244
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40021014;//0x40021000 [BASE] + 0x14 [OFFSET]
	uint32_t *pPortEModeReg = (uint32_t*)0x48001000;//0x48001000 [BASE] + 0x00 [OFFSET]
	uint32_t *pPortEOutReg =  (uint32_t*)0x48001014;//0x48001000 [BASE] + 0x14 [OFFSET]

	//1. enable the clock for GPOIE peripheral in the AHBENR (SET the 21st bit position)
	*pClkCtrlReg |= ( 1 << 21);

	//2. configure the mode of the IO pin 8 as output
	//a. clear the 16th and 17th bit positions (CLEAR)
	*pPortEModeReg &= ~( 3 << 16);
	//b. make 16th bit position as 1 (SET)
	*pPortEModeReg |= ( 1 << 16);

	//3.SET 8th bit of the output data register to make I/O pin-8 as HIGH
	*pPortEOutReg |= ( 1 << 8);

    while(1);
}
