/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{													//Pg 51, 52, 166, 243, 244
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40021014;//0x40021000 [BASE] + 0x14 [OFFSET]
	uint32_t *pPortEModeReg = (uint32_t*)0x48001000;//0x48001000 [BASE] + 0x00 [OFFSET]
	uint32_t *pPortEOutReg =  (uint32_t*)0x48001014;//0x48001000 [BASE] + 0x14 [OFFSET]

	uint32_t volatile *const pPortAModeReg = (uint32_t*)0x48000000;//0x48000000 [BASE] + 0x00 [OFFSET]
	uint32_t volatile *const pPortAInReg =   (uint32_t*)0x48000010;//0x48000000 [BASE] + 0x10 [OFFSET]

	//1. a. enable the clock for GPOIE peripheral in the AHBENR (SET the 21st bit position)
	*pClkCtrlReg |= ( 1 << 21);
	//1. b. enable the clock for GPIOA peripherals in the AHBENR (SET the 17th bit position)
	*pClkCtrlReg |= ( 1 << 17);
	
	//2. configure the mode of the IO pin 9 as output PE9
	//a. clear the 18th and 19th bit positions (CLEAR)
	*pPortEModeReg &= ~( 3 << 18);
	//b. make 16th bit position as 1 (SET)
	*pPortEModeReg |= ( 1 << 18);
	//c. Configure PA0 as input mode (GPIOA MODE REGISTER)
	*pPortAModeReg &= ~(3 << 0);// Please correct it Warning : IT CAN BE WRONG

	//3.SET 9th bit of the output data register to make I/O pin-9 as HIGH
	//*pPortEOutReg |= ( 1 << 9);

	while(1)
		{
			//3.read the pin status of the pin PA0 (GPIOA INPUT DATA REGISTER)
			uint8_t  pinStatus = (uint8_t)(*pPortAInReg & 0x1); //zero out all other bits except bit 0

			if(pinStatus){
				//turn on the LED
				*pPortEOutReg |= ( 1 << 9);
			}else{
				//turn off the LED
				*pPortEOutReg &= ~( 1 << 9);
			}

		}
}
